# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: Jerry the Migrator
:url: http://yourdomain.com
:copyright: 2013
:analytics_code: UA-00000000-0
