:headline: 
:body: |
  Hi, my name is Jerry.  I upgrade things.  Things like webapps written in
  Python or Ruby.

  You benefit from my services because your staff are working on the high value
  parts of your application.  Having them spend time learning how to do a
  certain upgrade is costly and since it is only done once, that knowledge is
  useless after the upgrade is complete.

  I do this repeatedly.  The knowledge I gain doing one upgrade carries
  over to the next.  It makes sense.

  <a href="mailto:jseutter@gmail.com?Subject=Solve%20my%20migration%20issues%21">
    Get in touch with me.
  </a>


  If you know of an Open Source project that needs my services, 
  <a href="mailto:jseutter@gmail.com?Subject=Solve%20my%20migration%20issues%21">
    get in touch with me.
  </a>
  I devote a portion of my time to working on Open Source.


